# This is a basic workflow to help you get started with Actions

name: Container Tag Latest

env:
  REPO_NAME: gent
  BUILDER_TAG: personal-finance-builder
  TESTER_TAG: personal-finance-tester
  IMPORT_TOOL_TAG: personal-finance-import-tool

# Controls when the workflow will run
on:
  # Makes this callable
  workflow_call:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  tag-latest:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      - name: Docker Login
        shell: bash
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          DOCKER_PASS: ${{ secrets.DOCKER_PASS }}
        run: |
          echo "$DOCKER_PASS" | docker login --username "$DOCKER_USER" --password-stdin

      - name: Tag Images Latest
        run: |
          docker pull "$REPO_NAME/$BUILDER_TAG:${{ github.sha }}"
          docker tag "$REPO_NAME/$BUILDER_TAG:${{ github.sha }}" "$REPO_NAME/$BUILDER_TAG:${{ github.ref_name }}"
          docker tag "$REPO_NAME/$BUILDER_TAG:${{ github.sha }}" "$REPO_NAME/$BUILDER_TAG:latest"
          docker push --all-tags $REPO_NAME/$BUILDER_TAG

          docker pull "$REPO_NAME/$TESTER_TAG:${{ github.sha }}"
          docker tag "$REPO_NAME/$TESTER_TAG:${{ github.sha }}" "$REPO_NAME/$TESTER_TAG:${{ github.ref_name }}"
          docker tag "$REPO_NAME/$TESTER_TAG:${{ github.sha }}" "$REPO_NAME/$TESTER_TAG:latest"
          docker push --all-tags $REPO_NAME/$TESTER_TAG

          docker pull "$REPO_NAME/$IMPORT_TOOL_TAG:${{ github.sha }}"
          docker tag "$REPO_NAME/$IMPORT_TOOL_TAG:${{ github.sha }}" "$REPO_NAME/$IMPORT_TOOL_TAG:${{ github.ref_name }}"
          docker tag "$REPO_NAME/$IMPORT_TOOL_TAG:${{ github.sha }}" "$REPO_NAME/$IMPORT_TOOL_TAG:latest"
          docker push --all-tags $REPO_NAME/$IMPORT_TOOL_TAG
