name: Container Workflow

env:
  CONTAINER_DIR: ./.github/workflows/container
  REPO_NAME: gent
  BUILDER_TAG: personal-finance-builder
  TESTER_TAG: personal-finance-tester
  IMPORT_TOOL_TAG: personal-finance-import-tool

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    # Run daily at 13:49
    - cron: "49 13 * * *"

jobs:
  checkout:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

  build-and-publish:
    uses: ./.github/workflows/container-build-and-publish.yml
    secrets: inherit
    needs: checkout

  codeQL:
    uses: ./.github/workflows/codeql-analysis.yml
    needs: checkout

  audit:
    uses: ./.github/workflows/container-audit.yml
    needs: build-and-publish

  test:
    uses: ./.github/workflows/container-test.yml
    needs: build-and-publish

  tag-latest:
    uses: ./.github/workflows/container-tag-latest.yml
    needs: [audit, test, codeQL]
    with:
      repo_name: $REPO_NAME
      container_tags: "$BUILDER_TAG, $TESTER_TAG, $IMPORT_TOOL_TAG"

  # promote:
  #   run: echo "Replace Staging/Production w/e you would like to do after you have a clean new version of the software."
