name: Dev Environment Health

env:
  WORK_DIR: .github/workflows
  DEV_ENV_COMPOSE_FILE: .devcontainer/docker-compose.yml

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test-dev-env:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
      # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Start Dev Environment
        run: docker compose -f $DEV_ENV_COMPOSE_FILE up -d

      - name: Wait until the environment is up
        run: $WORK_DIR/helpers/wait-until.sh "docker compose -f $DEV_ENV_COMPOSE_FILE logs | grep 'current.health=\"GREEN\"'"
        shell: bash

      - name: Check for Elk Server
        run: curl -s "http://0.0.0.0:9200" | grep 'elk'

      - name: Check for Kibana Server
        run: |
        curl 'http://localhost:5601/app/home' \
        -H 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8' \
        -H 'Accept-Language: en-US,en' \
        -H 'Connection: keep-alive' \
        -H 'Sec-Fetch-Dest: document' \
        -H 'Sec-Fetch-Mode: navigate' \
        -H 'Sec-Fetch-Site: none' \
        -H 'Sec-Fetch-User: ?1' \
        -H 'Sec-GPC: 1' \
        -H 'Upgrade-Insecure-Requests: 1' \
        -H 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36' \
        --compressed

      - name: Show compose log for debugging
        run: docker compose -f $DEV_ENV_COMPOSE_FILE logs
        if: always()


        