name: Dev Environment Health

env:
  WORK_DIR: .github/workflows
  DEV_ENV_COMPOSE_FILE: .devcontainer/docker-compose.yml

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test-dev-env:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
      # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Start Dev Environment
        run: docker compose -f $DEV_ENV_COMPOSE_FILE up -d

      - name: Wait until the environment is up
        run: $WORK_DIR/helpers/wait-until.sh "docker compose -f $DEV_ENV_COMPOSE_FILE logs | grep 'current.health=\"GREEN\"'"
        shell: bash

      - name: Check for Elk Server
        run: curl -s "http://0.0.0.0:9200" | grep 'elk'

      - name: Check for Kibana Server
        run: curl -L "http://localhost:5601/app/home"

      - name: Show compose log for debugging
        run: docker compose -f $DEV_ENV_COMPOSE_FILE logs
        if: always()